In [1]:
import pandas as pd
import altair as alt
import numpy as np
from vega_datasets import data
import streamlit as st

In [2]:
df = pd.read_csv('County_President/countypres_2000-2020.csv')

In [3]:
# drop unused columns and nulls
df = df.drop(columns=['mode', 'version', 'office'])
df = df.dropna()
df = df.reset_index()
df.shape

(72560, 10)

In [4]:
# drop counties reporting zero total votes
df = df.loc[df['totalvotes'] != 0]
df.shape

(72540, 10)

In [7]:
# get % of votes each party received in each county
temp = []

for index, row in df.iterrows():
    temp.append(round(row['candidatevotes'] / row['totalvotes'], 4))
df['percentage'] = temp

In [8]:
#create new dataframe with desired data config
curr_county = 'AUTAUGA'
new_df = []
temp_dict = {}
for index, row in df.iterrows():
    temp_dict['year'] = row['year']
    temp_dict['county'] = row['county_name']
    temp_dict['state'] = row['state_po']
    temp_dict['county_fips'] = int(row['county_fips'])
    temp_dict['total_no'] = row['totalvotes']
    curr_party = row['party'][0].lower()
    
    if row['county_name'] == curr_county:
        if curr_party == 'd':
            temp_dict['dem_no'] = row['candidatevotes']
            temp_dict['dem_pct'] = row['percentage']
        elif curr_party == 'r':
            temp_dict['rep_no'] = row['candidatevotes']
            temp_dict['rep_pct'] = row['percentage']
        elif curr_party == 'l':
            temp_dict['lib_no'] = row['candidatevotes']
            temp_dict['lib_pct'] = row['percentage']
        elif curr_party == 'g':
            temp_dict['grn_no'] = row['candidatevotes']
            temp_dict['grn_pct'] = row['percentage']
        else:
            temp_dict['oth_no'] = row['candidatevotes']
            temp_dict['oth_pct'] = row['percentage']
    else:
        copy = temp_dict.copy()
        new_df.append(copy)
        temp_dict.clear()
        
        temp_dict['year'] = row['year']
        temp_dict['county'] = row['county_name']
        temp_dict['state'] = row['state_po']
        temp_dict['county_fips'] = int(row['county_fips'])
        temp_dict['total_no'] = row['totalvotes']
        curr_party = row['party'][0].lower()

        if curr_party == 'd':
            temp_dict['dem_no'] = row['candidatevotes']
            temp_dict['dem_pct'] = row['percentage']
        elif curr_party == 'r':
            temp_dict['rep_no'] = row['candidatevotes']
            temp_dict['rep_pct'] = row['percentage']
        elif curr_party == 'l':
            temp_dict['lib_no'] = row['candidatevotes']
            temp_dict['lib_pct'] = row['percentage']
        elif curr_party == 'g':
            temp_dict['grn_no'] = row['candidatevotes']
            temp_dict['grn_pct'] = row['percentage']
        else:
            temp_dict['oth_no'] = row['candidatevotes']
            temp_dict['oth_pct'] = row['percentage']
    
    curr_county = row['county_name']
    

new_df = pd.DataFrame(new_df)

In [9]:
new_df = new_df.replace(np.nan, 0)
new_df

,year,county,state,county_fips,total_no,dem_no,dem_pct,rep_no,rep_pct,grn_no,grn_pct,oth_no,oth_pct,lib_no,lib_pct
0,2000,BALDWIN,AL,1003,56480,4942,0.2872,11993,0.6969,160.0,0.0093,113.0,0.0066,0.0,0.0000
1,2000,BARBOUR,AL,1005,10395,13997,0.2478,40872,0.7237,1033.0,0.0183,578.0,0.0102,0.0,0.0000
2,2000,BIBB,AL,1007,7101,5188,0.4991,5096,0.4902,46.0,0.0044,65.0,0.0063,0.0,0.0000
3,2000,BLOUNT,AL,1009,17973,2710,0.3816,4273,0.6017,52.0,0.0073,66.0,0.0093,0.0,0.0000
4,2000,BULLOCK,AL,1011,4904,4977,0.2769,12667,0.7048,154.0,0.0086,175.0,0.0097,0.0,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18915,2020,SWEETWATER,WY,56037,16698,882,0.1764,3957,0.7914,0.0,0.0000,90.0,0.0180,71.0,0.0142
18916,2020,TETON,WY,56039,14787,3823,0.2289,12229,0.7324,0.0,0.0000,296.0,0.0177,350.0,0.0210
18917,2020,UINTA,WY,56041,9459,9848,0.6660,4341,0.2936,0.0,0.0000,343.0,0.0232,255.0,0.0172
18918,2020,WASHAKIE,WY,56043,4032,1591,0.1682,7496,0.7925,0.0,0.0000,200.0,0.0211,172.0,0.0182
18919,2020,WESTON,WY,56045,3560,651,0.1615,3245,0.8048,0.0,0.0000,71.0,0.0176,65.0,0.0161